#anand_python 2:33
#Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.

def nearly_equal(str1,str2):
	print str1+' and '+str2
	if str1[-1] is str2[-1] and str1[0] is str2[0]:
		return True
	else:
		return False




if __name__ == '__main__':
	print nearly_equal('python','pearl')
	print nearly_equal('perl','pearl')
	print nearly_equal('python','jython')
	print nearly_equal('man','woman')
