# anand python 2:31# anand python 2:32# anand python 2:31
#Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character, replacing a character, or swapping 2 consecutive characters in a string. For simplicity consider only letters from a to z.
import random
def mutate(mut):
	# insetion mutation
	res=[]
	alfa=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','p','q','r','s','t','u','v','w','x','y','z']
	ins=[x[0]+mut[1:] for x in random.sample(alfa,1) ]
	print 'insertion at starting with random(a-z)' ,ins
	res.append(ins)

	#deleting 
	sec2=[]
	sec=random.sample(mut,1)
	for i in mut:
		if i is not  sec[0]:
			sec2.append(i)
		
	sec3=''.join(sec2)
	print 'delete:',sec3
	res.append(sec3)

	#swapping last two values 
	itera=[x for x in mut]
	
	tmp=itera[-2]
	itera[-2]=itera[-1]
	itera[-1]=tmp
	sec4=''.join(itera)
	res.append(sec4)
	print 'swap last values:',sec4

	
		

	


	

if __name__ == '__main__':
	mutate('hello')

